---
title: "TrabajoFinal"
author: "David M. Villalobo"
date: "2023-06-03"
output: html_document
---

```{r setup}
library(plyr)
BaseDatosFinal$Tipo <- mapvalues(BaseDatosFinal$Tipo, from = c("blade", "flake"), to = c(1,0))
```

## R Markdown


```{r cars}
library(ggplot2)
ggplot(BaseDatosFinal, aes(x = Longitud, y = Anchura, color = Tipo)) + geom_point()
```

## Including Plots


```{r pressure, echo=FALSE}
ggplot(BaseDatosFinal, aes(x = Grosor, y = Peso, color = Tipo)) + geom_point()
```


```{r}
BaseDatosFinal$Tipo_fac <- as.factor(BaseDatosFinal$Tipo)
BaseDatosFinal$Tipo_fac
```


```{r}
model <- glm(Tipo_fac ~ Anchura, data = BaseDatosFinal, family = binomial())
summary(model)
```
```{r}
model2 <- glm(Tipo_fac ~ Longitud, data = BaseDatosFinal, family = binomial())
summary(model2)
```

```{r}
model3 <- glm(Tipo_fac ~ Grosor, data = BaseDatosFinal, family = binomial())
summary(model3)
```

```{r}
model4 <- glm(Tipo_fac ~ Peso, data = BaseDatosFinal, family = binomial())
summary(model4)
```


```{r}
model_1 <- glm(Tipo_fac ~ Anchura + Longitud, data = BaseDatosFinal, family = binomial())
summary(model_1)
```
```{r}
model_2 <- glm(Tipo_fac ~ Grosor + Peso, data = BaseDatosFinal, family = binomial())
summary(model_2)
```

```{r}
model_3 <- glm(Tipo_fac ~ Anchura + Longitud + Grosor, data = BaseDatosFinal, family = binomial())
summary(model_3)
```

```{r}
model_4 <- glm(Tipo_fac ~ Anchura + Longitud + Grosor + Peso, data = BaseDatosFinal, family = binomial())
summary(model_4)
```

```{r}
model_5 <- glm(Tipo_fac ~ Longitud + Grosor + Peso, data = BaseDatosFinal, family = binomial())
summary(model_5)
```

```{r}
model_6 <- glm(Tipo_fac ~ Longitud + Grosor, data = BaseDatosFinal, family = binomial())
summary(model_6)
```

```{r}
model_7 <- glm(Tipo_fac ~ Longitud + Peso, data = BaseDatosFinal, family = binomial())
summary(model_7)
```


```{r}
BaseDatosFinal$Longitud_Anchura <- BaseDatosFinal$Longitud/BaseDatosFinal$Anchura
```

```{r}
model5 <- glm(Tipo_fac ~ Longitud_Anchura, data = BaseDatosFinal, family = binomial())
summary(model5)
```

```{r}
model_8 <- glm(Tipo_fac ~ Longitud_Anchura + Peso, data = BaseDatosFinal, family = binomial())
summary(model_8)
```


```{r}
model_9 <- glm(Tipo_fac ~ Longitud_Anchura + Grosor, data = BaseDatosFinal, family = binomial())
summary(model_9)
```


```{r}
mean(BaseDatosFinal$Longitud_Anchura [BaseDatosFinal$Tipo == "0"]) 

```

```{r}
mean(BaseDatosFinal$Longitud_Anchura [BaseDatosFinal$Tipo == "1"])
```



